name: Workflow for CI with GitHub Actions

on:
  push:
    branches:
      - main
      - develop

env:
  base_url: http://localhost:3000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check TypeScript Errors
        run: pnpm i -g typescript && tsc

      - name: Check ESLint Errors
        run: pnpm eslint

      - name: Check Lint Errors
        run: pnpm lint

      - name: Run Unit & Integration Tests
        run: pnpm test

      - name: Build Project
        run: pnpm run build

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: .next

  run-cypress-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .next

      - name: Install start-server-and-test
        run: pnpm add start-server-and-test

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: pnpm start
          wait-on: "http://localhost:3000" # Wait for the server to be up
          wait-on-timeout: 60 # Timeout in seconds
